/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  config_alert_instance: () => import("@/views/config/alert/instance/index.vue"),
  config_alert_policy: () => import("@/views/config/alert/policy/index.vue"),
  "config_cluster-add": () => import("@/views/config/cluster-add/index.vue"),
  "config_cluster-detail": () => import("@/views/config/cluster-detail/[id].vue"),
  "config_cluster-update": () => import("@/views/config/cluster-update/[id].vue"),
  config_cluster: () => import("@/views/config/cluster/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_schedule-add": () => import("@/views/manage/schedule-add/index.vue"),
  "manage_schedule-detail": () => import("@/views/manage/schedule-detail/[id].vue"),
  "manage_schedule-update": () => import("@/views/manage/schedule-update/[id].vue"),
  manage_schedule: () => import("@/views/manage/schedule/index.vue"),
  "manage_task-add": () => import("@/views/manage/task-add/index.vue"),
  "manage_task-detail": () => import("@/views/manage/task-detail/[id].vue"),
  "manage_task-update": () => import("@/views/manage/task-update/[id].vue"),
  manage_task: () => import("@/views/manage/task/index.vue"),
  manage_taskinstance: () => import("@/views/manage/taskinstance/index.vue"),
  "system_user-detail": () => import("@/views/system/user-detail/[id].vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
