/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router
export const generatedRoutes = [
    {
        name: '403',
        path: '/403',
        component: 'layout.blank$view.403',
        meta: {
            title: '403',
            i18nKey: 'route.403',
            constant: true,
            hideInMenu: true
        }
    },
    {
        name: '404',
        path: '/404',
        component: 'layout.blank$view.404',
        meta: {
            title: '404',
            i18nKey: 'route.404',
            constant: true,
            hideInMenu: true
        }
    },
    {
        name: '500',
        path: '/500',
        component: 'layout.blank$view.500',
        meta: {
            title: '500',
            i18nKey: 'route.500',
            constant: true,
            hideInMenu: true
        }
    },
    {
        name: 'config',
        path: '/config',
        component: 'layout.base',
        meta: {
            title: 'config',
            i18nKey: 'route.config',
            icon: 'mynaui:config-solid',
            order: 9
        },
        children: [
            {
                name: 'config_alert',
                path: '/config/alert',
                component: 'layout.base',
                meta: {
                    title: 'config_alert',
                    i18nKey: 'route.config_alert',
                    icon: 'material-symbols:edit-notifications-outline-rounded'
                },
                children: [
                    {
                        name: 'config_alert_instance',
                        path: '/config/alert/instance',
                        component: 'view.config_alert_instance',
                        meta: {
                            title: 'config_alert_instance',
                            i18nKey: 'route.config_alert_instance',
                            icon: 'material-symbols:calendar-view-month-outline'
                        }
                    },
                    {
                        name: 'config_alert_policy',
                        path: '/config/alert/policy',
                        component: 'view.config_alert_policy',
                        meta: {
                            title: 'config_alert_policy',
                            i18nKey: 'route.config_alert_policy',
                            icon: 'material-symbols:policy'
                        }
                    }
                ]
            },
            {
                name: 'config_cluster',
                path: '/config/cluster',
                component: 'view.config_cluster',
                meta: {
                    title: 'config_cluster',
                    i18nKey: 'route.config_cluster',
                    icon: 'eos-icons:cluster-outlined'
                }
            },
            {
                name: 'config_cluster-add',
                path: '/config/cluster-add',
                component: 'view.config_cluster-add',
                meta: {
                    title: 'config_cluster-add',
                    i18nKey: 'route.config_cluster-add',
                    hideInMenu: true
                }
            },
            {
                name: 'config_cluster-detail',
                path: '/config/cluster-detail/:id',
                component: 'view.config_cluster-detail',
                params: true,
                meta: {
                    title: 'config_cluster-detail',
                    i18nKey: 'route.config_cluster-detail',
                    hideInMenu: true
                }
            },
            {
                name: 'config_cluster-update',
                path: '/config/cluster-update/:id',
                component: 'view.config_cluster-update',
                params: true,
                meta: {
                    title: 'config_cluster-update',
                    i18nKey: 'route.config_cluster-update',
                    hideInMenu: true
                }
            }
        ]
    },
    {
        name: 'function',
        path: '/function',
        component: 'layout.base',
        meta: {
            title: 'function',
            i18nKey: 'route.function',
            icon: 'icon-park-outline:all-application',
            order: 6,
            hideInMenu: true
        },
        children: [
            {
                name: 'function_hide-child',
                path: '/function/hide-child',
                meta: {
                    title: 'function_hide-child',
                    i18nKey: 'route.function_hide-child',
                    icon: 'material-symbols:filter-list-off',
                    order: 2
                },
                redirect: '/function/hide-child/one',
                children: [
                    {
                        name: 'function_hide-child_one',
                        path: '/function/hide-child/one',
                        component: 'view.function_hide-child_one',
                        meta: {
                            title: 'function_hide-child_one',
                            i18nKey: 'route.function_hide-child_one',
                            icon: 'material-symbols:filter-list-off',
                            hideInMenu: true,
                            activeMenu: 'function_hide-child'
                        }
                    },
                    {
                        name: 'function_hide-child_three',
                        path: '/function/hide-child/three',
                        component: 'view.function_hide-child_three',
                        meta: {
                            title: 'function_hide-child_three',
                            i18nKey: 'route.function_hide-child_three',
                            hideInMenu: true,
                            activeMenu: 'function_hide-child'
                        }
                    },
                    {
                        name: 'function_hide-child_two',
                        path: '/function/hide-child/two',
                        component: 'view.function_hide-child_two',
                        meta: {
                            title: 'function_hide-child_two',
                            i18nKey: 'route.function_hide-child_two',
                            hideInMenu: true,
                            activeMenu: 'function_hide-child'
                        }
                    }
                ]
            },
            {
                name: 'function_multi-tab',
                path: '/function/multi-tab',
                component: 'view.function_multi-tab',
                meta: {
                    title: 'function_multi-tab',
                    i18nKey: 'route.function_multi-tab',
                    icon: 'ic:round-tab',
                    multiTab: true,
                    hideInMenu: true,
                    activeMenu: 'function_tab'
                }
            },
            {
                name: 'function_request',
                path: '/function/request',
                component: 'view.function_request',
                meta: {
                    title: 'function_request',
                    i18nKey: 'route.function_request',
                    icon: 'carbon:network-overlay',
                    order: 3
                }
            },
            {
                name: 'function_super-page',
                path: '/function/super-page',
                component: 'view.function_super-page',
                meta: {
                    title: 'function_super-page',
                    i18nKey: 'route.function_super-page',
                    icon: 'ic:round-supervisor-account',
                    order: 5,
                    roles: ['R_SUPER']
                }
            },
            {
                name: 'function_tab',
                path: '/function/tab',
                component: 'view.function_tab',
                meta: {
                    title: 'function_tab',
                    i18nKey: 'route.function_tab',
                    icon: 'ic:round-tab',
                    order: 1
                }
            },
            {
                name: 'function_toggle-auth',
                path: '/function/toggle-auth',
                component: 'view.function_toggle-auth',
                meta: {
                    title: 'function_toggle-auth',
                    i18nKey: 'route.function_toggle-auth',
                    icon: 'ic:round-construction',
                    order: 4
                }
            }
        ]
    },
    {
        name: 'home',
        path: '/home',
        component: 'layout.base$view.home',
        meta: {
            title: 'home',
            i18nKey: 'route.home',
            icon: 'mdi:monitor-dashboard',
            order: 1
        }
    },
    {
        name: 'iframe-page',
        path: '/iframe-page/:url',
        component: 'layout.base$view.iframe-page',
        props: true,
        meta: {
            title: 'iframe-page',
            i18nKey: 'route.iframe-page',
            constant: true,
            hideInMenu: true,
            keepAlive: true
        }
    },
    {
        name: 'login',
        path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
        component: 'layout.blank$view.login',
        props: true,
        meta: {
            title: 'login',
            i18nKey: 'route.login',
            constant: true,
            hideInMenu: true
        }
    },
    {
        name: 'manage',
        path: '/manage',
        component: 'layout.base',
        meta: {
            title: 'manage',
            i18nKey: 'route.manage',
            icon: 'carbon:cloud-service-management',
            order: 8,
            roles: ['R_ADMIN']
        },
        children: [
            {
                name: 'manage_menu',
                path: '/manage/menu',
                component: 'view.manage_menu',
                meta: {
                    title: 'manage_menu',
                    i18nKey: 'route.manage_menu',
                    icon: 'material-symbols:route',
                    order: 3,
                    roles: ['R_ADMIN'],
                    keepAlive: true,
                    hideInMenu: true
                }
            },
            {
                name: 'manage_role',
                path: '/manage/role',
                component: 'view.manage_role',
                meta: {
                    title: 'manage_role',
                    i18nKey: 'route.manage_role',
                    icon: 'carbon:user-role',
                    order: 2,
                    roles: ['R_SUPER'],
                    hideInMenu: true
                }
            },
            {
                name: 'manage_schedule',
                path: '/manage/schedule',
                component: 'view.manage_schedule',
                meta: {
                    title: 'manage_schedule',
                    i18nKey: 'route.manage_schedule',
                    icon: 'material-symbols:schedule-outline-rounded',
                    order: 2
                }
            },
            {
                name: 'manage_schedule-add',
                path: '/manage/schedule-add',
                component: 'view.manage_schedule-add',
                meta: {
                    title: 'manage_schedule-add',
                    i18nKey: 'route.manage_schedule-add',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_schedule-detail',
                path: '/manage/schedule-detail/:id',
                component: 'view.manage_schedule-detail',
                meta: {
                    title: 'manage_schedule-detail',
                    i18nKey: 'route.manage_schedule-detail',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_schedule-update',
                path: '/manage/schedule-update/:id',
                component: 'view.manage_schedule-update',
                meta: {
                    title: 'manage_schedule-update',
                    i18nKey: 'route.manage_schedule-update',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_task',
                path: '/manage/task',
                component: 'view.manage_task',
                meta: {
                    title: 'manage_task',
                    i18nKey: 'route.manage_task',
                    icon: 'material-symbols:folder-managed-outline-rounded',
                    order: 1
                }
            },
            {
                name: 'manage_task-add',
                path: '/manage/task-add',
                component: 'view.manage_task-add',
                meta: {
                    title: 'manage_task-add',
                    i18nKey: 'route.manage_task-add',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_task-detail',
                path: '/manage/task-detail/:id',
                component: 'view.manage_task-detail',
                meta: {
                    title: 'manage_task-detail',
                    i18nKey: 'route.manage_task-detail',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_task-update',
                path: '/manage/task-update/:id',
                component: 'view.manage_task-update',
                meta: {
                    title: 'manage_task-update',
                    i18nKey: 'route.manage_task-update',
                    hideInMenu: true
                }
            },
            {
                name: 'manage_taskinstance',
                path: '/manage/taskinstance',
                component: 'view.manage_taskinstance',
                meta: {
                    title: 'manage_taskinstance',
                    i18nKey: 'route.manage_taskinstance',
                    icon: 'material-symbols:table-outline'
                }
            }
        ]
    },
    {
        name: 'system',
        path: '/system',
        component: 'layout.base',
        meta: {
            title: 'system',
            i18nKey: 'route.system',
            icon: 'ic:round-settings-applications',
            order: 7
        },
        children: [
            {
                name: 'system_user',
                path: '/system/user',
                component: 'view.system_user',
                meta: {
                    title: 'system_user',
                    i18nKey: 'route.system_user',
                    icon: 'ic:round-manage-accounts',
                    roles: ['R_ADMIN']
                }
            },
            {
                name: 'system_user-detail',
                path: '/system/user-detail/:id',
                component: 'view.system_user-detail',
                props: true,
                meta: {
                    title: 'system_user-detail',
                    i18nKey: 'route.system_user-detail',
                    hideInMenu: true,
                    roles: ['R_ADMIN'],
                    activeMenu: 'system_user'
                }
            }
        ]
    },
    {
        name: 'user-center',
        path: '/user-center',
        component: 'layout.base$view.user-center',
        meta: {
            title: 'user-center',
            i18nKey: 'route.user-center',
            hideInMenu: true
        }
    }
];
