/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router
/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(routes, layouts, views) {
    return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}
/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(route, layouts, views) {
    const LAYOUT_PREFIX = 'layout.';
    const VIEW_PREFIX = 'view.';
    const ROUTE_DEGREE_SPLITTER = '_';
    const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';
    function isLayout(component) {
        return component.startsWith(LAYOUT_PREFIX);
    }
    function getLayoutName(component) {
        const layout = component.replace(LAYOUT_PREFIX, '');
        if (!layouts[layout]) {
            throw new Error(`Layout component "${layout}" not found`);
        }
        return layout;
    }
    function isView(component) {
        return component.startsWith(VIEW_PREFIX);
    }
    function getViewName(component) {
        const view = component.replace(VIEW_PREFIX, '');
        if (!views[view]) {
            throw new Error(`View component "${view}" not found`);
        }
        return view;
    }
    function isFirstLevelRoute(item) {
        return !item.name.includes(ROUTE_DEGREE_SPLITTER);
    }
    function isSingleLevelRoute(item) {
        return isFirstLevelRoute(item) && !item.children?.length;
    }
    function getSingleLevelRouteComponent(component) {
        const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);
        return {
            layout: getLayoutName(layout),
            view: getViewName(view)
        };
    }
    const vueRoutes = [];
    // add props: true to route
    if (route.path.includes(':') && !route.props) {
        route.props = true;
    }
    const { name, path, component, children, ...rest } = route;
    const vueRoute = { name, path, ...rest };
    try {
        if (component) {
            if (isSingleLevelRoute(route)) {
                const { layout, view } = getSingleLevelRouteComponent(component);
                const singleLevelRoute = {
                    path,
                    component: layouts[layout],
                    meta: {
                        title: route.meta?.title || ''
                    },
                    children: [
                        {
                            name,
                            path: '',
                            component: views[view],
                            ...rest
                        }
                    ]
                };
                return [singleLevelRoute];
            }
            if (isLayout(component)) {
                const layoutName = getLayoutName(component);
                vueRoute.component = layouts[layoutName];
            }
            if (isView(component)) {
                const viewName = getViewName(component);
                vueRoute.component = views[viewName];
            }
        }
    }
    catch (error) {
        console.error(`Error transforming route "${route.name}": ${error.toString()}`);
        return [];
    }
    // add redirect to child
    if (children?.length && !vueRoute.redirect) {
        vueRoute.redirect = {
            name: children[0].name
        };
    }
    if (children?.length) {
        const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));
        if (isFirstLevelRoute(route)) {
            vueRoute.children = childRoutes;
        }
        else {
            vueRoutes.push(...childRoutes);
        }
    }
    vueRoutes.unshift(vueRoute);
    return vueRoutes;
}
/**
 * map of route name and route path
 */
const routeMap = {
    "root": "/",
    "not-found": "/:pathMatch(.*)*",
    "exception": "/exception",
    "exception_403": "/exception/403",
    "exception_404": "/exception/404",
    "exception_500": "/exception/500",
    "document": "/document",
    "document_project": "/document/project",
    "document_project-link": "/document/project-link",
    "document_vue": "/document/vue",
    "document_vite": "/document/vite",
    "document_unocss": "/document/unocss",
    "document_naive": "/document/naive",
    "document_antd": "/document/antd",
    "403": "/403",
    "404": "/404",
    "500": "/500",
    "config": "/config",
    "config_alert": "/config/alert",
    "config_alert_instance": "/config/alert/instance",
    "config_alert_policy": "/config/alert/policy",
    "config_cluster": "/config/cluster",
    "config_cluster-add": "/config/cluster-add",
    "config_cluster-detail": "/config/cluster-detail/:id",
    "config_cluster-update": "/config/cluster-update/:id",
    "function": "/function",
    "function_hide-child": "/function/hide-child",
    "function_hide-child_one": "/function/hide-child/one",
    "function_hide-child_three": "/function/hide-child/three",
    "function_hide-child_two": "/function/hide-child/two",
    "function_multi-tab": "/function/multi-tab",
    "function_request": "/function/request",
    "function_super-page": "/function/super-page",
    "function_tab": "/function/tab",
    "function_toggle-auth": "/function/toggle-auth",
    "home": "/home",
    "iframe-page": "/iframe-page/:url",
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
    "manage": "/manage",
    "manage_menu": "/manage/menu",
    "manage_role": "/manage/role",
    "manage_schedule": "/manage/schedule",
    "manage_schedule-add": "/manage/schedule-add",
    "manage_schedule-detail": "/manage/schedule-detail/:id",
    "manage_schedule-update": "/manage/schedule-update/:id",
    "manage_task": "/manage/task",
    "manage_task-add": "/manage/task-add",
    "manage_task-detail": "/manage/task-detail/:id",
    "manage_task-update": "/manage/task-update/:id",
    "manage_taskinstance": "/manage/taskinstance",
    "manage_user": "/manage/user",
    "manage_user-detail": "/manage/user-detail/:id",
    "user-center": "/user-center"
};
/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath(name) {
    return routeMap[name];
}
/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path) {
    const routeEntries = Object.entries(routeMap);
    const routeName = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;
    return routeName;
}
